### ISSUE TITLE
Myclass.class is not a preference entity.

### ISSUE THREAD

**Issue by tsironis13** [skydoves/PreferenceRoom#8]
I have created Preference Component inside app module:

@PreferenceComponent(entities = Myclass.class)
public interface MyComponent {
    void inject(MyActivity _);
}

Myclass preference entity is located inside another android library module and I am getting the following build error:
'error: ==================== ERROR LOG ====================
library.package.Myclass.class is not a preference entity.'. 

When I move entity class to app module my application is built successfully.

**Comment by skydoves** [comment]
@tsironis13 
Hello!
The `PreferenceComponent` and `Entity` should be inside in the same package.
Because in the annotation processor, the processor can only work in one module.
So If you want to separate to multi-module, you should move `component` together.

You can reference this posting about [Creating Clean Architecture Multi-Project App](https://proandroiddev.com/creating-clean-architecture-multi-project-mvp-app-34d753a187ad).
Section - Room for Data layer.
